import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
    flexDirection: 'column',
    // paddingTop: 20,
  },
  contentLayout: {
    flex: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
  },
  inputView: {
    width: '80%',
    backgroundColor: '#465881',
    borderRadius: 25,
    height: 50,
    marginBottom: 20,
    justifyContent: 'center',
    padding: 20,
  },
  inputText: {
    fontFamily: 'THSarabunNew Bold',
    height: 50,
    color: 'white',
  },
  forgot: {
    color: 'white',
    fontSize: 11,
  },
  logOutBtn: {
    width: '80%',
    backgroundColor: '#FFFFFF',
    borderWidth: 7,
    borderColor: '#ff6600',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    marginBottom: 10,
  },
  logOutText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#ff8514',
    fontSize: 22,
  },
  menuContentView: {
    width: '80%',
    backgroundColor: '#ffcc99',
    borderRadius: 0,
    height: 50,
    marginBottom: 20,
    // justifyContent: 'center',
    padding: 20,
    borderLeftWidth: 10,
    borderLeftColor: '#ff9900',
    paddingVertical: 15,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  menuHeaderText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#ff6600',
    fontSize: 22,
    marginLeft: 20,
  },
  menuText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#ff6600',
    fontSize: 32,
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  menuIcon: {
    fontFamily: 'THSarabunNew Bold',
    color: '#FFF',
    fontSize: 30,
    textAlignVertical: 'center',
    textAlign: 'center',
    backgroundColor: '#ff9900',
    borderRadius: 30,
  },
  headerLayout: {
    flex: 3,
    backgroundColor: '#ff9900',
    justifyContent: 'center',
    marginBottom: 10,
  },
  headerText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#FFF',
    fontSize: 30,
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  headerStyle: {
    width: '100%',
    height: 50,
    backgroundColor: '#ff8514',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  contentCenter: {
    textAlignVertical: 'center',
    textAlign: 'center',
    alignItems: 'center',
  },
  lineHeader: {
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    textAlignVertical: 'center',
    textAlign: 'center',
    width: '40%',
  },
  footerLayout: {
    flex: 2,
    backgroundColor: '#f99339',
    justifyContent: 'center',
  },
  footerStyle: {
    fontFamily: 'THSarabunNew Bold',
    width: '100%',
    height: 50,
    backgroundColor: '#ff8514',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  footerText: {
    fontFamily: 'THSarabunNew Bold',
    fontSize: 20,
    color: '#FFF',
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  bottomFooter: {
    flex: 0.2,
    backgroundColor: '#ff6600',
  },
  headerLine: {
    borderBottomColor: 'white',
    borderBottomWidth: 1,
  },
  subHeaderLayout: {
    flex: 1,
    justifyContent: 'center',
  },
});

export {styles};
