import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
    flexDirection: 'column',
    // paddingTop: 20,
  },
  headerLayout: {
    flex: 1.2,
    backgroundColor: '#ff6600',
    justifyContent: 'center',
  },
  subHeaderLayout: {
    flex: 1,
    backgroundColor: '#FF9934',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  headerText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#FFF',
    fontSize: 30,
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  subHeaderText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#FFF',
    fontSize: 22,
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  lineHeader: {
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    textAlignVertical: 'center',
    textAlign: 'center',
    width: '40%',
  },
  headerLine: {
    borderBottomColor: 'white',
    borderBottomWidth: 1,
  },
  inputView: {
    width: '80%',
    backgroundColor: '#E68B30',
    borderRadius: 25,
    height: 20,
    marginHorizontal: 5,
    marginVertical: 5,
    padding: 20,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputText: {
    fontFamily: 'THSarabunNew Bold',
    fontSize: 24,
    height: 50,
    color: 'white',
  },
  searchIcon: {
    flex: 0.1,
    padding: 10,
  },
  addIcon: {
    flex: 5,
    height: 50,
    padding: 10,
  },
  contentCenter: {
    textAlignVertical: 'center',
    textAlign: 'center',
    alignItems: 'center',
  },
  contentLayout: {
    flex: 10,
    alignItems: 'center',
    paddingTop: 10,
  },
  bottomFooter: {
    flex: 0.2,
    backgroundColor: '#ff6600',
  },
  itemContentView: {
    flex: 0.2,
    width: '90%',
    backgroundColor: '#F2F2F2',
    borderRadius: 0,
    height: 50,
    marginBottom: 20,
    // justifyContent: 'center',
    padding: 20,
    borderLeftWidth: 5,
    borderLeftColor: '#ff9900',
    paddingVertical: 0,
    paddingHorizontal: 0,
    flexDirection: 'column',
    // justifyContent: 'space-between',
    // alignItems: 'center',
  },
  subItemTop: {
    flex: 1.2,
    width: '100%',
    backgroundColor: '#F2F2F2',
    borderRadius: 0,
    // height: 100,
    // justifyContent: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  subItemBottom: {
    flex: 0.7,
    backgroundColor: '#E3E7EA',
    borderRadius: 0,
    // justifyContent: 'center',
    // paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  rowStyle: {
    flex: 1,
  },
  itemHeaderText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#ff6600',
    fontSize: 22,
    marginLeft: 20,
  },
  itemText: {
    fontFamily: 'THSarabunNew Bold',
    color: '#ff6600',
    fontSize: 26,
    // textAlignVertical: 'center',
    // textAlign: 'center',
  },
  itemTextDetail: {
    fontFamily: 'THSarabunNew Bold',
    color: '#ff6600',
    fontSize: 20,
    // textAlignVertical: 'center',
    // textAlign: 'center',
  },
  itemTextTopic: {
    fontFamily: 'THSarabunNew Bold',
    color: '#000',
    fontSize: 26,
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  itemIcon: {
    flex: 0.2,
    fontFamily: 'THSarabunNew Bold',
    color: '#ff6600',
    fontSize: 30,
    textAlignVertical: 'center',
    textAlign: 'center',
    borderRadius: 30,
  },
  redDot: {
    height: 10,
    width: 10,
    backgroundColor: 'red',
    borderRadius: 50,
    display: 'flex',
  },
  greenDot: {
    height: 10,
    width: 10,
    backgroundColor: 'green',
    borderRadius: 50,
    display: 'flex',
  },
  yellowDot: {
    height: 10,
    width: 10,
    backgroundColor: 'yellow',
    borderRadius: 50,
    display: 'flex',
  }
});

export {styles};
